language: java
sudo: false
before_script:
  - _JAVA_OPTIONS="-Xmx4096m -Xms2048m"

script:
  - mvn clean compile assembly:single
  - mvn -Dtest=FrontendTests test
  - mvn -Dtest=RuntimeTests test
  - mvn -Dtest=SparkRuntimeTests test


